name: Release Pipeline
on:
  push:
    branches:
      - master

env:
  PROJECT_PATH: Telegram.Cli/Telegram.Cli.csproj

jobs:
  set_release_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Define next release version
        id: set_version
        run: echo "version=$(cat Telegram.Cli/Telegram.Cli.csproj | grep -oP '(?<=<AssemblyVersion>).*(?=<\/AssemblyVersion>)')" >> $GITHUB_ENV

  build:
    needs: set_release_version
    permissions:
      deployments: write
      contents: write
    strategy:
      matrix:
        include:
          - platform: win-x64
            artifact_suffix: windows
            exe_name: tme.exe
          - platform: linux-x64
            artifact_suffix: linux
            exe_name: tme
          - platform: osx-x64
            artifact_suffix: macos
            exe_name: tme
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.set_release_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish Project
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --framework net6.0 --runtime ${{ matrix.platform }} --self-contained true /p:PublishSingleFile=true /p:DebugType=None

      - name: Compressing artifact
        run: zip -j "telegramCli_${{ env.VERSION }}_${{ matrix.artifact_suffix }}.zip" ./Telegram.Cli/bin/Release/net6.0/${{ matrix.platform }}/publish/${{ matrix.exe_name }} # the -j flag is used to remove the folder structure from the zip file 

      - name: Uploading artifact
        id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: "telegramCli_${{ env.VERSION }}_${{ matrix.artifact_suffix }}"
          path: "telegramCli_${{ env.VERSION }}_${{ matrix.artifact_suffix }}.zip"
          if-no-files-found: error

  deploy:
    needs: [set_release_version, build]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact_suffix: [windows, linux, macos]
    env:
      VERSION: ${{ needs.set_release_version.outputs.version }}
    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v3
        with:
          name: "telegramCli_${{ env.VERSION }}_${{ matrix.artifact_suffix }}"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: "telegramCli_${{ env.VERSION }}_${{ matrix.artifact_suffix }}.zip"
