name: .NET Core Test Pipeline

on:
  push:
    branches: [ '**' ]

env:
  PROJECT_PATH: Telegram.Cli/Telegram.Cli.csproj

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.PROJECT_PATH }} --no-build --verbosity normal
